// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import {
  Body,
  Controller,
  Delete,
  Get,
  Param,
  ParseIntPipe,
  Patch,
  Post,
} from '@nestjs/common';
import {
  ApiOperation,
  ApiParam,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import { UserAppService } from './user-app.service';
import { AddUserToAppDto } from './dto/add-user-to-app.dto';
import { CreateUserAppDto } from './dto/create-user-app.dto';
import { UpdateUserAppDto } from './dto/update-user-app.dto';

@ApiTags('user-app')
@Controller('user-app')
export class UserAppController {
  constructor(private readonly service: UserAppService) {}

  @Post()
  @ApiOperation({ summary: '创建用户应用关系' })
  @ApiResponse({ status: 201, description: '创建成功' })
  create(@Body() body: CreateUserAppDto) {
    return this.service.create(body);
  }

  @Post('app/:appId/users')
  @ApiOperation({ summary: '向应用添加用户' })
  @ApiParam({ name: 'appId', type: Number })
  @ApiResponse({ status: 201, description: '添加成功' })
  addUser(
    @Param('appId', ParseIntPipe) appId: number,
    @Body() body: AddUserToAppDto,
  ) {
    return this.service.addUser(appId, body);
  }

  @Get()
  @ApiOperation({ summary: '查询用户应用关系列表' })
  findAll() {
    return this.service.findAll();
  }

  @Get(':id')
  @ApiOperation({ summary: '按 ID 查询用户应用关系' })
  @ApiParam({ name: 'id', type: Number })
  findOne(@Param('id', ParseIntPipe) id: number) {
    return this.service.findOne(id);
  }

  @Patch(':id')
  @ApiOperation({ summary: '按 ID 更新用户应用关系' })
  @ApiParam({ name: 'id', type: Number })
  update(
    @Param('id', ParseIntPipe) id: number,
    @Body() body: UpdateUserAppDto,
  ) {
    return this.service.update(id, body);
  }

  @Delete(':id')
  @ApiOperation({ summary: '按 ID 删除用户应用关系' })
  @ApiParam({ name: 'id', type: Number })
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.service.remove(id);
  }
}
