// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { UserAppService } from './user-app.service';
import { UserAppController } from './user-app.controller';

@Module({
  providers: [UserAppService],
  controllers: [UserAppController],
  exports: [UserAppService],
})
export class UserAppModule {}
