// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '../../../generated/prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { AddUserToAppDto } from './dto/add-user-to-app.dto';
import { CreateUserAppDto } from './dto/create-user-app.dto';
import { UpdateUserAppDto } from './dto/update-user-app.dto';

@Injectable()
export class UserAppService {
  constructor(private readonly prisma: PrismaService) {}

  async create(body: CreateUserAppDto) {
    await this.ensureBaseEntities(body.userId, body.appId, body.roleId);
    await this.ensureUniqueUserApp(body.userId, body.appId);
    try {
      return await this.prisma.userApp.create({
        data: {
          userId: body.userId,
          appId: body.appId,
          roleId: body.roleId,
        },
      });
    } catch (error) {
      this.rethrowPrismaError(error);
      throw error;
    }
  }

  async findAll() {
    return this.prisma.userApp.findMany({
      include: {
        user: { select: { id: true, email: true, username: true } },
        appClient: { select: { id: true, name: true, dsn: true } },
        role: { select: { id: true, name: true, allowToolLevel: true } },
      },
      orderBy: { id: 'asc' },
    });
  }

  async findOne(id: number) {
    const row = await this.prisma.userApp.findUnique({
      where: { id },
      include: {
        user: { select: { id: true, email: true, username: true } },
        appClient: { select: { id: true, name: true, dsn: true } },
        role: { select: { id: true, name: true, allowToolLevel: true } },
      },
    });
    if (!row) {
      throw new NotFoundException(`user-app ${id} not found`);
    }
    return row;
  }

  async update(id: number, body: UpdateUserAppDto) {
    const current = await this.findOne(id);
    const nextUserId = body.userId ?? current.userId;
    const nextAppId = body.appId ?? current.appId;
    const nextRoleId = body.roleId ?? current.roleId;
    await this.ensureBaseEntities(nextUserId, nextAppId, nextRoleId);
    await this.ensureUniqueUserApp(nextUserId, nextAppId, id);
    return this.prisma.userApp.update({
      where: { id },
      data: {
        userId: body.userId,
        appId: body.appId,
        roleId: body.roleId,
      },
      include: {
        user: { select: { id: true, email: true, username: true } },
        appClient: { select: { id: true, name: true, dsn: true } },
        role: { select: { id: true, name: true, allowToolLevel: true } },
      },
    });
  }

  async remove(id: number) {
    await this.findOne(id);
    return this.prisma.userApp.delete({ where: { id } });
  }

  async addUser(appId: number, body: AddUserToAppDto) {
    return this.create({ userId: body.userId, appId, roleId: body.roleId });
  }

  private async ensureBaseEntities(userId: number, appId: number, roleId: number) {
    const [user, appClient, role] = await Promise.all([
      this.prisma.user.findUnique({
        where: { id: userId },
        select: { id: true },
      }),
      this.prisma.appClient.findUnique({
        where: { id: appId },
        select: { id: true },
      }),
      this.prisma.role.findUnique({
        where: { id: roleId },
        select: { id: true },
      }),
    ]);
    if (!user) {
      throw new NotFoundException(`user ${userId} not found`);
    }
    if (!appClient) {
      throw new NotFoundException(`app-client ${appId} not found`);
    }
    if (!role) {
      throw new NotFoundException(`role ${roleId} not found`);
    }
  }

  private async ensureUniqueUserApp(userId: number, appId: number, currentId?: number) {
    let exists: { id: number } | null = null;
    try {
      exists = await this.prisma.userApp.findUnique({
        where: {
          userId_appId: {
            userId,
            appId,
          },
        },
        select: { id: true },
      });
    } catch (error) {
      this.rethrowPrismaError(error);
      throw error;
    }
    if (exists && exists.id !== currentId) {
      throw new BadRequestException(`user ${userId} already in app ${appId}`);
    }
  }

  private rethrowPrismaError(error: unknown): never | void {
    if (!(error instanceof Prisma.PrismaClientKnownRequestError)) {
      return;
    }
    if (error.code === 'P2002') {
      throw new BadRequestException('user already exists in app');
    }
    if (error.code === 'P2021' || error.code === 'P2022') {
      throw new BadRequestException(
        'database schema is outdated, please run latest prisma migration',
      );
    }
  }
}
