// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { SessionService } from './session.service';

@Controller('session')
export class SessionController {
  constructor(private readonly service: SessionService) {}
}
