// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class SessionService {
  // TODO: inject PrismaService and implement session queries.
}
