// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class SkillToolService {
  // TODO: inject PrismaService and implement skillTool queries.
}
