// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { SkillToolService } from './skill-tool.service';
import { SkillToolController } from './skill-tool.controller';

@Module({
  providers: [SkillToolService],
  controllers: [SkillToolController],
  exports: [SkillToolService],
})
export class SkillToolModule {}
