// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { SkillToolService } from './skill-tool.service';

@Controller('skill-tool')
export class SkillToolController {
  constructor(private readonly service: SkillToolService) {}
}
