// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class MessageService {
  // TODO: inject PrismaService and implement message queries.
}
