// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class AppClientService {
  // TODO: inject PrismaService and implement appClient queries.
}
