// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { AppClientService } from './app-client.service';
import { AppClientController } from './app-client.controller';

@Module({
  providers: [AppClientService],
  controllers: [AppClientController],
  exports: [AppClientService],
})
export class AppClientModule {}
