// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import {
  Body,
  Controller,
  Delete,
  Get,
  Param,
  ParseIntPipe,
  Patch,
  Post,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiOperation,
  ApiParam,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import { AppClientService } from './app-client.service';
import { CreateAppClientDto } from './dto/create-app-client.dto';
import { UpdateAppClientDto } from './dto/update-app-client.dto';

@ApiTags('admin-app-client')
@ApiBearerAuth()
@Controller('/app-client')
export class AppClientController {
  constructor(private readonly service: AppClientService) {}

  @Post()
  @ApiOperation({ summary: '管理员创建业务 AppClient' })
  @ApiResponse({ status: 201, description: '创建成功' })
  create(@Body() body: CreateAppClientDto) {
    return this.service.create(body);
  }

  @Get()
  @ApiOperation({ summary: '管理员查询 AppClient 列表' })
  findAll() {
    return this.service.findAll();
  }

  @Get(':id')
  @ApiParam({ name: 'id', type: Number })
  @ApiOperation({ summary: '管理员按 ID 查询 AppClient' })
  findOne(@Param('id', ParseIntPipe) id: number) {
    return this.service.findOne(id);
  }

  @Patch(':id')
  @ApiParam({ name: 'id', type: Number })
  @ApiOperation({ summary: '管理员按 ID 更新 AppClient' })
  update(
    @Param('id', ParseIntPipe) id: number,
    @Body() body: UpdateAppClientDto,
  ) {
    return this.service.update(id, body);
  }

  @Delete(':id')
  @ApiParam({ name: 'id', type: Number })
  @ApiOperation({ summary: '管理员按 ID 删除 AppClient' })
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.service.remove(id);
  }
}
