// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import {
  BadRequestException,
  Injectable,
  NotFoundException,
  UnauthorizedException,
} from '@nestjs/common';
import { randomBytes } from 'crypto';
import { Prisma } from '../../../generated/prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestAppClient } from '../../auth/request-app-client';
import { UserService } from '../user/user.service';
import { CreateAppClientDto } from './dto/create-app-client.dto';
import { UpdateAppClientDto } from './dto/update-app-client.dto';
import { AppClientAuthService } from './auth/app-client-auth.service';
import { parseAppClientAuthConfig } from './auth/app-client-auth.config.util';

@Injectable()
export class AppClientService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly userService: UserService,
    private readonly appClientAuthService: AppClientAuthService,
  ) {}

  async create(dto: CreateAppClientDto) {
    const name = dto.name?.trim();
    if (!name) {
      throw new BadRequestException('name is required');
    }
    const dsn = await this.generateUniqueDsn();
    return this.prisma.appClient.create({
      data: {
        name,
        dsn,
        description: dto.description?.trim() || null,
        isActive: dto.isActive ?? true,
      },
    });
  }

  async findAll() {
    return this.prisma.appClient.findMany({
      orderBy: { id: 'asc' },
    });
  }

  async findOne(id: number) {
    const row = await this.prisma.appClient.findUnique({ where: { id } });
    if (!row) {
      throw new NotFoundException(`appClient ${id} not found`);
    }
    return row;
  }

  async update(id: number, dto: UpdateAppClientDto) {
    await this.findOne(id);
    const data: Prisma.AppClientUpdateInput = {
      name: dto.name?.trim(),
      description:
        dto.description === undefined ? undefined : dto.description.trim(),
      isActive: dto.isActive,
    };
    if (dto.authConfig !== undefined) {
      if (dto.authConfig === null) {
        data.authConfig = Prisma.DbNull;
      } else {
        data.authConfig = parseAppClientAuthConfig(dto.authConfig);
      }
    }
    try {
      return await this.prisma.appClient.update({
        where: { id },
        data,
      });
    } catch (error) {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === 'P2025'
      ) {
        throw new NotFoundException(`appClient ${id} not found`);
      }
      throw error;
    }
  }

  async remove(id: number) {
    await this.findOne(id);
    const blockers = await this.collectAppClientDeleteBlockers(id);
    if (blockers.length > 0) {
      throw new BadRequestException(
        `appClient ${id} cannot be deleted while referenced by: ${blockers.join(', ')}`,
      );
    }
    try {
      return await this.prisma.appClient.delete({ where: { id } });
    } catch (error) {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === 'P2003'
      ) {
        throw new BadRequestException(
          `appClient ${id} is referenced by other records and cannot be deleted`,
        );
      }
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === 'P2025'
      ) {
        throw new NotFoundException(`appClient ${id} not found`);
      }
      throw error;
    }
  }

  /** 删除前检查各子资源是否仍有关联（有则不可删）。 */
  private async collectAppClientDeleteBlockers(
    appClientId: number,
  ): Promise<string[]> {
    const [
      agents,
      tools,
      sessions,
      messageTurns,
      agentRuns,
      integrations,
      userApps,
      promptTemplates,
      skills,
    ] = await this.prisma.$transaction([
      this.prisma.agent.count({ where: { appClientId } }),
      this.prisma.tool.count({ where: { appClientId } }),
      this.prisma.session.count({ where: { appClientId } }),
      this.prisma.messageTurn.count({ where: { appClientId } }),
      this.prisma.agentRun.count({ where: { appClientId } }),
      this.prisma.integration.count({ where: { appClientId } }),
      this.prisma.userApp.count({ where: { appId: appClientId } }),
      this.prisma.promptTemplate.count({ where: { appClientId } }),
      this.prisma.skill.count({ where: { agent: { appClientId } } }),
    ]);

    const parts: string[] = [];
    if (agents > 0) {
      parts.push(`${agents} agent(s)`);
    }
    if (tools > 0) {
      parts.push(`${tools} tool(s)`);
    }
    if (integrations > 0) {
      parts.push(`${integrations} integration(s)`);
    }
    if (skills > 0) {
      parts.push(`${skills} skill(s)`);
    }
    if (userApps > 0) {
      parts.push(`${userApps} user-app binding(s)`);
    }
    if (sessions > 0) {
      parts.push(`${sessions} session(s)`);
    }
    if (messageTurns > 0) {
      parts.push(`${messageTurns} message turn(s)`);
    }
    if (agentRuns > 0) {
      parts.push(`${agentRuns} agent run(s)`);
    }
    if (promptTemplates > 0) {
      parts.push(`${promptTemplates} prompt template(s)`);
    }
    return parts;
  }

  /**
   * 前台 SDK 认证：DSN + 业务 accountToken。
   * 外部账号校验通过后：按 employeeId 自动建档/复用 User；若无 UserApp 则自动绑定当前 App（默认 operator 角色）。
   */
  async authenticate(
    appClientId: number,
    accountToken: string,
    appClient: RequestAppClient | undefined,
  ) {
    const token = accountToken.trim();
    if (!token) {
      throw new UnauthorizedException('x-account-token is required');
    }

    const profile = await this.appClientAuthService.verifyAccountToken(
      appClientId,
      token,
    );
    if (!profile.active) {
      throw new UnauthorizedException('external account is inactive');
    }

    const authConfig =
      await this.appClientAuthService.loadResolvedAuthConfig(appClientId);
    const user = await this.userService.findOrCreateByExternalAccount(profile);
    this.userService.assertUserIsActive(user.status);
    const userAppCreated = await this.ensureUserAppBinding(
      user.id,
      appClientId,
      authConfig.autoBindRoleName ?? 'operator',
    );
    if (authConfig.propagateTokenToIntegrations !== false) {
      await this.bindUserIntegrations(user.id, appClientId, token);
    }

    const accessToken = await this.userService.signUserAccessToken({
      id: user.id,
      email: user.email,
      username: user.username,
    });

    return {
      ok: true,
      appClient,
      accessToken,
      user,
      accountTokenBound: true,
      userAppCreated,
    };
  }

  async testAuth(appClientId: number, accountToken: string) {
    await this.findOne(appClientId);
    return this.appClientAuthService.testAccountToken(appClientId, accountToken);
  }

  /** 外部鉴权通过后确保 UserApp 存在；缺失时按配置角色自动绑定。 */
  private async ensureUserAppBinding(
    userId: number,
    appClientId: number,
    autoBindRoleName: string,
  ): Promise<boolean> {
    const existing = await this.prisma.userApp.findUnique({
      where: {
        userId_appId: {
          userId,
          appId: appClientId,
        },
      },
      select: { id: true },
    });
    if (existing) {
      return false;
    }
    const roleId = await this.resolveAutoBindRoleId(autoBindRoleName);
    try {
      await this.prisma.userApp.create({
        data: {
          userId,
          appId: appClientId,
          roleId,
        },
      });
      return true;
    } catch (error) {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === 'P2002'
      ) {
        // 并发重复 auth：另一请求已创建同一 userId+appId 绑定
        return false;
      }
      throw error;
    }
  }

  private async resolveAutoBindRoleId(roleName: string): Promise<number> {
    const normalized = roleName.trim().toLowerCase() || 'operator';
    const role = await this.prisma.role.findUnique({
      where: { name: normalized },
      select: { id: true },
    });
    if (!role) {
      throw new BadRequestException(
        `default auth role "${normalized}" not found; run db:seed or configure autoBindRoleName`,
      );
    }
    return role.id;
  }

  private async bindUserIntegrations(
    userId: number,
    appClientId: number,
    accountToken: string,
  ): Promise<void> {
    const integrations = await this.prisma.integration.findMany({
      where: { appClientId },
      select: { id: true },
    });
    if (integrations.length === 0) {
      return;
    }
    await this.prisma.$transaction(
      integrations.map((integration) =>
        this.prisma.userIntegration.upsert({
          where: {
            userId_integrationId: {
              userId,
              integrationId: integration.id,
            },
          },
          create: {
            userId,
            integrationId: integration.id,
            userApiKey: accountToken,
            isActive: true,
          },
          update: {
            userApiKey: accountToken,
            isActive: true,
          },
        }),
      ),
    );
  }

  private createRandomDsn(): string {
    return randomBytes(16).toString('hex');
  }

  private async generateUniqueDsn(): Promise<string> {
    let candidate = this.createRandomDsn();
    while (true) {
      const existing = await this.prisma.appClient.findUnique({
        where: { dsn: candidate },
        select: { id: true },
      });
      if (!existing) {
        return candidate;
      }
      candidate = this.createRandomDsn();
    }
  }
}
