// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { AppClientService } from './app-client.service';

@Controller('app-client')
export class AppClientController {
  constructor(private readonly service: AppClientService) {}
}
