// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { AuthModule } from '../../auth/auth.module';
import { AppClientAuthService } from './auth/app-client-auth.service';
import { AppClientService } from './app-client.service';
import { AppClientController } from './app-client.controller';
import { UserModule } from '../user/user.module';

@Module({
  imports: [AuthModule, UserModule],
  providers: [AppClientService, AppClientAuthService],
  controllers: [AppClientController],
  exports: [AppClientService, AppClientAuthService],
})
export class AppClientModule {}
