// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { UserLlmModelConfigService } from './user-llm-model-config.service';

@Controller('user-llm-model-config')
export class UserLlmModelConfigController {
  constructor(private readonly service: UserLlmModelConfigService) {}
}
