// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { UserLlmModelConfigService } from './user-llm-model-config.service';
import { UserLlmModelConfigController } from './user-llm-model-config.controller';

@Module({
  providers: [UserLlmModelConfigService],
  controllers: [UserLlmModelConfigController],
  exports: [UserLlmModelConfigService],
})
export class UserLlmModelConfigModule {}
