// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class UserLlmModelConfigService {
  // TODO: inject PrismaService and implement userLlmModelConfig queries.
}
