// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { AdminUserService } from './admin-user.service';

@Controller('admin-user')
export class AdminUserController {
  constructor(private readonly service: AdminUserService) {}
}
