// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import {
  BadRequestException,
  Injectable,
  UnauthorizedException,
} from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { scryptSync, timingSafeEqual } from 'crypto';
import type { AdminUser } from '../../../generated/prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { LoginAdminUserDto } from './dto/login-admin-user.dto';

@Injectable()
export class AdminUserService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly jwtService: JwtService,
  ) {}

  private verifyPassword(
    plainPassword: string,
    storedPassword: string,
  ): boolean {
    const [salt, hash] = storedPassword.split(':');
    if (!salt || !hash) {
      return false;
    }
    const hashBytes = Uint8Array.from(Buffer.from(hash, 'hex'));
    const plainHashBuffer = scryptSync(plainPassword, salt, hashBytes.length);
    const plainHashBytes = Uint8Array.from(plainHashBuffer);
    return timingSafeEqual(hashBytes, plainHashBytes);
  }

  private sanitizeAdminUser(user: AdminUser) {
    const { password, ...rest } = user;
    return rest;
  }

  async login(data: LoginAdminUserDto) {
    const email = data.email?.trim();
    const password = data.password?.trim();

    if (!email || !password) {
      throw new BadRequestException('email and password are required');
    }

    const admin = await this.prisma.adminUser.findFirst({
      where: { email, isActive: true },
    });
    if (!admin) {
      throw new UnauthorizedException('invalid email or password');
    }

    const verified = this.verifyPassword(password, admin.password);
    if (!verified) {
      throw new UnauthorizedException('invalid email or password');
    }

    const payload = {
      sub: admin.id,
      email: admin.email,
      username: admin.username,
      adminRole: admin.role,
    };
    const accessToken = await this.jwtService.signAsync(payload);

    return {
      accessToken,
      user: this.sanitizeAdminUser(admin),
      mustChangePassword: admin.mustChangePassword,
    };
  }
}
