// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class AdminUserService {
  // TODO: inject PrismaService and implement adminUser queries.
}
