// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Body, Controller, Post } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { AdminUserService } from './admin-user.service';
import { LoginAdminUserDto } from './dto/login-admin-user.dto';

@ApiTags('admin-user')
@Controller('admin-user')
export class AdminUserController {
  constructor(private readonly service: AdminUserService) {}

  @Post('login')
  @ApiOperation({ summary: '管理员登录' })
  @ApiResponse({ status: 200, description: '登录成功并返回 JWT Token' })
  @ApiResponse({ status: 401, description: '邮箱或密码错误' })
  login(@Body() body: LoginAdminUserDto) {
    return this.service.login(body);
  }
}
