// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import {
  Body,
  Controller,
  Get,
  Post,
  Req,
  UnauthorizedException,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiOperation,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import type { Request } from 'express';
import { AdminUserService } from './admin-user.service';
import { AdminUserProfileDto } from './dto/admin-user-profile.dto';
import { LoginAdminUserDto } from './dto/login-admin-user.dto';

@ApiTags('admin-user')
@Controller('admin-user')
export class AdminUserController {
  constructor(private readonly service: AdminUserService) {}

  @Post('login')
  @ApiOperation({ summary: '管理员登录' })
  @ApiResponse({ status: 200, description: '登录成功并返回 JWT Token' })
  @ApiResponse({ status: 401, description: '邮箱或密码错误' })
  login(@Body() body: LoginAdminUserDto) {
    return this.service.login(body);
  }

  @Get('me')
  @ApiBearerAuth()
  @ApiOperation({
    summary: '获取当前登录管理员信息',
    description:
      '需 `Authorization: Bearer <管理员 JWT>`。AppClient `http_profile` 鉴权可将本接口作为 profilePath（见 app-client id=2 配置）。',
  })
  @ApiResponse({ status: 200, type: AdminUserProfileDto })
  @ApiResponse({ status: 401, description: 'Token 无效或管理员不可用' })
  getMe(@Req() req: Request & { user?: { userId?: number } }) {
    const userId = req.user?.userId;
    if (userId == null) {
      throw new UnauthorizedException('missing admin user context');
    }
    return this.service.getProfileByUserId(userId);
  }
}
