// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { UserRoleToolService } from './user-role-tool.service';

@Controller('user-role-tool')
export class UserRoleToolController {
  constructor(private readonly service: UserRoleToolService) {}
}
