// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { UserRoleToolService } from './user-role-tool.service';
import { UserRoleToolController } from './user-role-tool.controller';

@Module({
  providers: [UserRoleToolService],
  controllers: [UserRoleToolController],
  exports: [UserRoleToolService],
})
export class UserRoleToolModule {}
