// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class UserRoleToolService {
  // TODO: inject PrismaService and implement userRoleTool queries.
}
