// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class SkillService {
  // TODO: inject PrismaService and implement skill queries.
}
