// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class IntegrationService {
  // TODO: inject PrismaService and implement integration queries.
}
