// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class LlmModelConfigService {
  // TODO: inject PrismaService and implement llmModelConfig queries.
}
