// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { LlmModelConfigService } from './llm-model-config.service';

@Controller('llm-model-config')
export class LlmModelConfigController {
  constructor(private readonly service: LlmModelConfigService) {}
}
