// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { LlmModelConfigService } from './llm-model-config.service';
import { LlmModelConfigController } from './llm-model-config.controller';

@Module({
  providers: [LlmModelConfigService],
  controllers: [LlmModelConfigController],
  exports: [LlmModelConfigService],
})
export class LlmModelConfigModule {}
