// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { AgentSkillService } from './agent-skill.service';
import { AgentSkillController } from './agent-skill.controller';

@Module({
  providers: [AgentSkillService],
  controllers: [AgentSkillController],
  exports: [AgentSkillService],
})
export class AgentSkillModule {}
