// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { AgentSkillService } from './agent-skill.service';

@Controller('agent-skill')
export class AgentSkillController {
  constructor(private readonly service: AgentSkillService) {}
}
