// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class AgentSkillService {
  // TODO: inject PrismaService and implement agentSkill queries.
}
