// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { UserAppRoleService } from './user-app-role.service';

@Controller('user-app-role')
export class UserAppRoleController {
  constructor(private readonly service: UserAppRoleService) {}
}
