// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class UserAppRoleService {
  // TODO: inject PrismaService and implement userAppRole queries.
}
