// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { UserAppRoleService } from './user-app-role.service';
import { UserAppRoleController } from './user-app-role.controller';

@Module({
  providers: [UserAppRoleService],
  controllers: [UserAppRoleController],
  exports: [UserAppRoleService],
})
export class UserAppRoleModule {}
