// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class RoleService {
  // TODO: inject PrismaService and implement role queries.
}
