// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { ToolCategoryService } from './tool-category.service';
import { ToolCategoryController } from './tool-category.controller';

@Module({
  providers: [ToolCategoryService],
  controllers: [ToolCategoryController],
  exports: [ToolCategoryService],
})
export class ToolCategoryModule {}
