// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { ToolCategoryService } from './tool-category.service';

@Controller('tool-category')
export class ToolCategoryController {
  constructor(private readonly service: ToolCategoryService) {}
}
