// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class ToolCategoryService {
  // TODO: inject PrismaService and implement toolCategory queries.
}
