// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class AgentEntity {
  id?: number;
  name: string;
  config?: unknown | null;
  createdAt?: Date;
  agentSkills: RelationRef[];
}
