// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class IntegrationEntity {
  id?: number;
  appClientId: number;
  name: string;
  baseUrl: string;
  apiKey?: string | null;
  authMode: 'USER_ONLY' | 'SYSTEM_ONLY' | 'USER_PREFERRED';
  appClient: RelationRef;
  tools: RelationRef[];
  createdAt?: Date;
  updatedAt?: Date;
}
