// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class RoleSkillEntity {
  id?: number;
  roleId: number;
  skillId: number;
  role: RelationRef;
  skill: RelationRef;
}
