// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class RoleEntity {
  id?: number;
  name: string;
  description?: string | null;
  allowToolLevel?: RelationRef;
  createdAt?: Date;
  users: RelationRef[];
  roleSkills: RelationRef[];
}
