// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class SessionEntity {
  id: string;
  userId: number;
  appClientId: number;
  agentId?: number | null;
  title?: string | null;
  createdAt?: Date;
  user: RelationRef;
  appClient: RelationRef;
  messages: RelationRef[];
  agentRuns: RelationRef[];
}
