// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class SkillEntity {
  id?: number;
  name: string;
  description?: string | null;
  prompt: string;
  config?: unknown | null;
  createdAt?: Date;
  skillTools: RelationRef[];
  agentSkills: RelationRef[];
}
