// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class SkillToolEntity {
  id?: number;
  skillId: number;
  toolId: number;
  skill: RelationRef;
  tool: RelationRef;
}
