// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class ToolEntity {
  id?: number;
  appClientId: number;
  /** 业务能力键：同一 appClient 内唯一，跨 App 可对齐 */
  definitionKey: string;
  name: string;
  description: string;
  riskLevel?: RelationRef;
  schema: unknown;
  skillTools: RelationRef[];
  inputSchema: unknown;
  outputSchema?: unknown | null;
  method: RelationRef;
  path: string;
  integrationId: number;
  integration: RelationRef;
  appClient: RelationRef;
  toolCategoryId?: number | null;
  toolCategory?: RelationRef | null;
  roleTools: RelationRef[];
  isActive?: boolean;
  timeout?: number | null;
  createdAt?: Date;
  updatedAt?: Date;
}
