// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class ToolCategoryEntity {
  id?: number;
  label: string;
  description?: string | null;
  sortOrder?: number;
  tools: RelationRef[];
  createdAt?: Date;
  updatedAt?: Date;
}
