// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class UserAppEntity {
  id?: number;
  userId: number;
  appId: number;
  createdAt?: Date;
  user: RelationRef;
  appClient: RelationRef;
  userAppRoles: RelationRef[];
}
