// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class UserAppRoleEntity {
  id?: number;
  userId: number;
  appId: number;
  roleId: number;
  createdAt?: Date;
  user: RelationRef;
  appClient: RelationRef;
  role: RelationRef;
  userApp: RelationRef;
}
