// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class UserEntity {
  id?: number;
  email: string;
  password: string;
  username: string;
  roleId?: number | null;
  mustChangePassword?: boolean;
  createdAt?: Date;
  sessions: RelationRef[];
  llmModelConfigs: RelationRef[];
  role?: RelationRef | null;
}
