// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export class UserEntity {
  id?: number;
  email: string;
  password: string;
  username: string;
  token?: string | null;
  createdAt?: Date;
  sessions: RelationRef[];
  llmModelConfigs: RelationRef[];
}
