// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class AgentService {
  // TODO: inject PrismaService and implement agent queries.
}
