// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { AgentService } from './agent.service';
import { AgentController } from './agent.controller';
import { AgentCacheStore } from './agent-cache.store';

@Module({
  providers: [AgentService, AgentCacheStore],
  controllers: [AgentController],
  exports: [AgentService],
})
export class AgentModule {}
