// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export interface AgentSkillType {
  id?: number;
  agentId: number;
  skillId: number;
  agent: RelationRef;
  skill: RelationRef;
}
