// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export interface IntegrationType {
  id?: number;
  appClientId: number;
  name: string;
  baseUrl: string;
  apiKey: string;
  appClient: RelationRef;
  tools: RelationRef[];
  createdAt?: Date;
}
