// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export interface SessionType {
  id?: number;
  userId: number;
  agentId?: number | null;
  title?: string | null;
  createdAt?: Date;
  user: RelationRef;
  messages: RelationRef[];
}
