// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export interface ToolType {
  id?: number;
  name: string;
  description: string;
  riskLevel?: RelationRef;
  schema: unknown;
  createdAt?: Date;
  skillTools: RelationRef[];
}
