// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export interface UserType {
  id?: number;
  username: string;
  createdAt?: Date;
  sessions: RelationRef[];
}
