// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import type { RelationRef } from '../shared/relation-ref';

export interface UserRoleToolType {
  id?: number;
  userRole: RelationRef;
  toolId: number;
  createdAt?: Date;
  tool: RelationRef;
}
