// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { AgentRunService } from './agent-run.service';
import { AgentRunController } from './agent-run.controller';

@Module({
  providers: [AgentRunService],
  controllers: [AgentRunController],
  exports: [AgentRunService],
})
export class AgentRunModule {}
