// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class AgentRunService {
  // TODO: inject PrismaService and implement agentRun queries.
}
