// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { AgentRunService } from './agent-run.service';

@Controller('agent-run')
export class AgentRunController {
  constructor(private readonly service: AgentRunService) {}
}
