import * as fs from 'fs';
import * as path from 'path';

type FieldMeta = {
  name: string;
  type: string;
  isOptional: boolean;
  isList: boolean;
  rawAttributes: string;
  hasDefault: boolean;
  isUpdatedAt: boolean;
  isRelation: boolean;
};

type ModelMeta = {
  name: string;
  fields: FieldMeta[];
};

type CliOptions = {
  schemaPath: string;
  outDir: string;
  dryRun: boolean;
  overwrite: boolean;
  models?: Set<string>;
  withService: boolean;
  withController: boolean;
};

const GENERATED_HEADER =
  '// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.\n';
const SCALAR_TYPES = new Set([
  'String',
  'Boolean',
  'Int',
  'Float',
  'Decimal',
  'BigInt',
  'DateTime',
  'Json',
  'Bytes',
]);

function parseArgs(argv: string[]): CliOptions {
  const getArgValue = (flag: string): string | undefined => {
    const index = argv.indexOf(flag);
    if (index >= 0 && index < argv.length - 1) {
      return argv[index + 1];
    }
    return undefined;
  };

  const modelsValue = getArgValue('--models');
  const models = modelsValue
    ? new Set(
        modelsValue
          .split(',')
          .map((item) => item.trim())
          .filter(Boolean),
      )
    : undefined;

  return {
    schemaPath: getArgValue('--schema') ?? 'prisma/schema.prisma',
    outDir: getArgValue('--out-dir') ?? 'src/',
    dryRun: argv.includes('--dry-run'),
    overwrite: argv.includes('--overwrite'),
    models,
    withService: argv.includes('--with-service'),
    withController: argv.includes('--with-controller'),
  };
}

function toKebabCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase();
}

function lowerFirst(value: string): string {
  return value.charAt(0).toLowerCase() + value.slice(1);
}

export function mapPrismaTypeToTs(type: string): string {
  const map: Record<string, string> = {
    String: 'string',
    Boolean: 'boolean',
    Int: 'number',
    Float: 'number',
    Decimal: 'number',
    BigInt: 'bigint',
    DateTime: 'Date',
    Json: 'unknown',
    Bytes: 'Buffer',
  };

  return map[type] ?? type;
}

export function parseSchemaModels(schema: string): ModelMeta[] {
  const modelRegex = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
  const models: ModelMeta[] = [];
  let match: RegExpExecArray | null;

  while ((match = modelRegex.exec(schema)) !== null) {
    const [, modelName, body] = match;
    const lines = body
      .split('\n')
      .map((line) => line.trim())
      .filter(
        (line) => line && !line.startsWith('//') && !line.startsWith('@@'),
      );

    const fields: FieldMeta[] = [];

    for (const line of lines) {
      const fieldMatch = line.match(/^(\w+)\s+([^\s]+)(.*)$/);
      if (!fieldMatch) {
        continue;
      }

      const [, name, rawType, attrs] = fieldMatch;
      const isList = rawType.endsWith('[]');
      const isOptional = rawType.endsWith('?');
      const cleanType = rawType.replace(/\?|\[\]/g, '');

      fields.push({
        name,
        type: cleanType,
        isOptional,
        isList,
        rawAttributes: attrs,
        hasDefault: attrs.includes('@default'),
        isUpdatedAt: attrs.includes('@updatedAt'),
        isRelation: !SCALAR_TYPES.has(cleanType),
      });
    }

    models.push({ name: modelName, fields });
  }

  return models.sort((a, b) => a.name.localeCompare(b.name));
}

function renderTypeFile(model: ModelMeta): string {
  const lines = model.fields.map((field) => {
    const optional =
      field.isOptional || field.hasDefault || field.isUpdatedAt ? '?' : '';
    const baseType = field.isRelation
      ? 'RelationRef'
      : mapPrismaTypeToTs(field.type);
    const tsType = field.isList ? `${baseType}[]` : baseType;
    const nullable = field.isOptional ? ' | null' : '';
    return `  ${field.name}${optional}: ${tsType}${nullable};`;
  });

  return `${GENERATED_HEADER}import type { RelationRef } from '../shared/relation-ref';\n\nexport interface ${
    model.name
  }Type {\n${lines.join('\n')}\n}\n`;
}

function renderEntityFile(model: ModelMeta): string {
  const lines = model.fields.map((field) => {
    const optional =
      field.isOptional || field.hasDefault || field.isUpdatedAt ? '?' : '';
    const baseType = field.isRelation
      ? 'RelationRef'
      : mapPrismaTypeToTs(field.type);
    const tsType = field.isList ? `${baseType}[]` : baseType;
    const nullable = field.isOptional ? ' | null' : '';
    return `  ${field.name}${optional}: ${tsType}${nullable};`;
  });

  return `${GENERATED_HEADER}import type { RelationRef } from '../shared/relation-ref';\n\nexport class ${
    model.name
  }Entity {\n${lines.join('\n')}\n}\n`;
}

function renderModuleFile(model: ModelMeta): string {
  const moduleClass = `${model.name}Module`;
  const serviceClass = `${model.name}Service`;
  const controllerClass = `${model.name}Controller`;
  const folder = toKebabCase(model.name);
  const hasService = `./${folder}.service`;
  const hasController = `./${folder}.controller`;

  return `${GENERATED_HEADER}import { Module } from '@nestjs/common';\nimport { ${serviceClass} } from '${hasService}';\nimport { ${controllerClass} } from '${hasController}';\n\n@Module({\n  providers: [${serviceClass}],\n  controllers: [${controllerClass}],\n  exports: [${serviceClass}],\n})\nexport class ${moduleClass} {}\n`;
}

function renderServiceFile(model: ModelMeta): string {
  const serviceClass = `${model.name}Service`;
  const modelVar = lowerFirst(model.name);
  return `${GENERATED_HEADER}import { Injectable } from '@nestjs/common';\n\n@Injectable()\nexport class ${serviceClass} {\n  // TODO: inject PrismaService and implement ${modelVar} queries.\n}\n`;
}

function renderControllerFile(model: ModelMeta): string {
  const controllerClass = `${model.name}Controller`;
  const serviceClass = `${model.name}Service`;
  const route = toKebabCase(model.name);
  return `${GENERATED_HEADER}import { Controller } from '@nestjs/common';\nimport { ${serviceClass} } from './${route}.service';\n\n@Controller('${route}')\nexport class ${controllerClass} {\n  constructor(private readonly service: ${serviceClass}) {}\n}\n`;
}

function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function shouldProtectFile(filePath: string, overwrite: boolean): boolean {
  if (!fs.existsSync(filePath)) {
    return false;
  }

  if (overwrite) {
    return false;
  }

  const current = fs.readFileSync(filePath, 'utf-8');
  return !current.startsWith(GENERATED_HEADER);
}

function writeIfChanged(
  filePath: string,
  content: string,
  options: { dryRun: boolean; overwrite: boolean },
  logs: string[],
): void {
  const exists = fs.existsSync(filePath);
  const current = exists ? fs.readFileSync(filePath, 'utf-8') : undefined;

  if (shouldProtectFile(filePath, options.overwrite)) {
    logs.push(`[skip:protected] ${filePath}`);
    return;
  }

  if (current === content) {
    logs.push(`[skip:unchanged] ${filePath}`);
    return;
  }

  if (options.dryRun) {
    logs.push(`${exists ? '[update]' : '[create]'} ${filePath}`);
    return;
  }

  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf-8');
  logs.push(`${exists ? '[updated]' : '[created]'} ${filePath}`);
}

function generateIndexFile(
  baseDir: string,
  fileNames: string[],
  options: { dryRun: boolean; overwrite: boolean },
  logs: string[],
): void {
  const lines = fileNames.sort().map((name) => `export * from './${name}';`);
  const content = `${GENERATED_HEADER}${lines.join('\n')}\n`;
  writeIfChanged(path.join(baseDir, 'index.ts'), content, options, logs);
}

function renderSharedRelationRefFile(): string {
  return `${GENERATED_HEADER}export type RelationRef = { id: number | string };\n`;
}

export function run(): void {
  const options = parseArgs(process.argv.slice(2));
  const schemaFullPath = path.resolve(process.cwd(), options.schemaPath);

  if (!fs.existsSync(schemaFullPath)) {
    throw new Error(`Schema file not found: ${schemaFullPath}`);
  }

  const schema = fs.readFileSync(schemaFullPath, 'utf-8');
  const parsedModels = parseSchemaModels(schema);
  const models = options.models
    ? parsedModels.filter((model) => options.models?.has(model.name))
    : parsedModels;

  if (models.length === 0) {
    throw new Error('No models matched for code generation.');
  }

  const outputRoot = path.resolve(process.cwd(), options.outDir);
  const typesDir = path.join(outputRoot, 'types');
  const entitiesDir = path.join(outputRoot, 'entities');
  const modulesDir = path.join(outputRoot, 'modules');
  const sharedDir = path.join(outputRoot, 'shared');
  const logs: string[] = [];

  writeIfChanged(
    path.join(sharedDir, 'relation-ref.ts'),
    renderSharedRelationRefFile(),
    options,
    logs,
  );

  for (const model of models) {
    writeIfChanged(
      path.join(typesDir, `${toKebabCase(model.name)}.type.ts`),
      renderTypeFile(model),
      options,
      logs,
    );
    writeIfChanged(
      path.join(entitiesDir, `${toKebabCase(model.name)}.entity.ts`),
      renderEntityFile(model),
      options,
      logs,
    );

    const moduleFolder = path.join(modulesDir, toKebabCase(model.name));
    writeIfChanged(
      path.join(moduleFolder, `${toKebabCase(model.name)}.module.ts`),
      renderModuleFile(model),
      options,
      logs,
    );

    if (options.withService) {
      writeIfChanged(
        path.join(moduleFolder, `${toKebabCase(model.name)}.service.ts`),
        renderServiceFile(model),
        options,
        logs,
      );
    }

    if (options.withController) {
      writeIfChanged(
        path.join(moduleFolder, `${toKebabCase(model.name)}.controller.ts`),
        renderControllerFile(model),
        options,
        logs,
      );
    }
  }

  generateIndexFile(
    typesDir,
    models.map((model) => `${toKebabCase(model.name)}.type`),
    options,
    logs,
  );
  generateIndexFile(
    entitiesDir,
    models.map((model) => `${toKebabCase(model.name)}.entity`),
    options,
    logs,
  );

  const moduleExports = models
    .map((model) => {
      const moduleName = toKebabCase(model.name);
      return `export * from './${moduleName}/${moduleName}.module';`;
    })
    .join('\n');
  writeIfChanged(
    path.join(modulesDir, 'index.ts'),
    `${GENERATED_HEADER}${moduleExports}\n`,
    options,
    logs,
  );

  const summary = options.dryRun ? 'Dry run summary:' : 'Generation summary:';
  // eslint-disable-next-line no-console
  console.log(summary);
  logs.forEach((line) => {
    // eslint-disable-next-line no-console
    console.log(`- ${line}`);
  });
}

if (require.main === module) {
  run();
}
