// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { RoleSkillService } from './role-skill.service';
import { RoleSkillController } from './role-skill.controller';

@Module({
  providers: [RoleSkillService],
  controllers: [RoleSkillController],
  exports: [RoleSkillService],
})
export class RoleSkillModule {}
