// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class RoleSkillService {
  // TODO: inject PrismaService and implement roleSkill queries.
}
