// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { RoleSkillService } from './role-skill.service';

@Controller('role-skill')
export class RoleSkillController {
  constructor(private readonly service: RoleSkillService) {}
}
