// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Module } from '@nestjs/common';
import { RoleToolService } from './role-tool.service';
import { RoleToolController } from './role-tool.controller';

@Module({
  providers: [RoleToolService],
  controllers: [RoleToolController],
  exports: [RoleToolService],
})
export class RoleToolModule {}
