// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';

@Injectable()
export class RoleToolService {
  // TODO: inject PrismaService and implement roleTool queries.
}
