// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { RoleToolService } from './role-tool.service';

@Controller('role-tool')
export class RoleToolController {
  constructor(private readonly service: RoleToolService) {}
}
