// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Injectable } from '@nestjs/common';
import {PrismaService} from "../../prisma/prisma.service";


@Injectable()
export class ToolService {
  // TODO: inject PrismaService and implement tool queries.


}
