// AUTO-GENERATED BY prisma-schema-codegen. DO NOT EDIT.
import { Controller } from '@nestjs/common';
import { ToolService } from './tool.service';

@Controller('tool')
export class ToolController {
  constructor(private readonly service: ToolService) {}
}
